fixes indentation

diff --git a/utils/bootstrap-link b/utils/bootstrap-link
--- a/utils/bootstrap-link
+++ b/utils/bootstrap-link
@@ -3,8 +3,8 @@
 set -e
 
 [[ -n $DOTFILES ]] || {
-    echo "[ERROR] \$DOTFILES is not set"
-    exit 1
+  echo "[ERROR] \$DOTFILES is not set"
+  exit 1
 }
 
 ln -nfs "$DOTFILES/etc/zshrc" ~/.zshrc
